from django.conf import settings

CURRENCIES = {
    "EUR": "€",
    "USD": "$",
    "GBP": "£",
    "JPY": "¥",
    "CHF": "Fr",
    "CAD": "C$",
    "AUD": "A$",
    "CNY": "¥",
    "INR": "₹",
    "BRL": "R$",
    "KRW": "₩",
    "MXN": "MX$",
    "SEK": "kr",
    "NOK": "kr",
    "DKK": "kr",
    "PLN": "zł",
    "TRY": "₺",
    "ZAR": "R",
    "RUB": "₽",
    "THB": "฿",
    "SGD": "S$",
    "HKD": "HK$",
    "NZD": "NZ$",
    "AED": "د.إ",
    "SAR": "﷼",
}

LANGUAGE_FLAGS = {
    "en": "🇺🇸",
    "es": "🇪🇸",
    "pt": "🇵🇹",
    "pl": "🇵🇱",
    "fr": "🇫🇷",
    "de": "🇩🇪",
    "it": "🇮🇹",
    "ro": "🇷🇴",
    "ru": "🇷🇺",
    "uk": "🇺🇦",
    "nl": "🇳🇱",
    "sv": "🇸🇪",
    "nb": "🇳🇴",
    "da": "🇩🇰",
    "fi": "🇫🇮",
    "cs": "🇨🇿",
    "sk": "🇸🇰",
    "hu": "🇭🇺",
    "tr": "🇹🇷",
    "el": "🇬🇷",
    "bg": "🇧🇬",
    "sr": "🇷🇸",
    "hr": "🇭🇷",
    "sl": "🇸🇮",
    "et": "🇪🇪",
    "lv": "🇱🇻",
    "lt": "🇱🇹",
    "ja": "🇯🇵",
    "ko": "🇰🇷",
    "zh-hans": "🇨🇳",
    "zh-hant": "🇹🇼",
    "ar": "🇸🇦",
    "he": "🇮🇱",
    "hi": "🇮🇳",
    "bn": "🇧🇩",
    "ur": "🇵🇰",
    "fa": "🇮🇷",
    "id": "🇮🇩",
    "ms": "🇲🇾",
    "th": "🇹🇭",
    "vi": "🇻🇳",
    "tl": "🇵🇭",
    "sw": "🇰🇪",
    "ca": "🏴",
    "eu": "🏴",
    "gl": "🏴",
    "is": "🇮🇸",
    "ga": "🇮🇪",
    "mt": "🇲🇹",
    "sq": "🇦🇱",
}

def currency_ctx(request):
    sym = request.session.get("currency", settings.CURRENCY_SYMBOL)
    code = request.session.get("currency_code", settings.CURRENCY_CODE)
    language_options = [
        {"code": lang_code, "label": lang_label, "flag": LANGUAGE_FLAGS.get(lang_code, "🌐")}
        for lang_code, lang_label in settings.LANGUAGES
    ]
    return {
        "currency_symbol": sym,
        "currency_code": code,
        "currencies": CURRENCIES,
        "language_options": language_options,
    }
