# Generated by Django 6.0.4 on 2026-05-05 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorybudget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budget',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categorybudget',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('owner', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='categorybudget',
            unique_together={('owner', 'month', 'category')},
        ),
    ]
